server:
  servlet:
    context-path: /

spring:
  application:
    name: PManager
  datasource:
    # url: jdbc:h2:mem:test
    # driverClassName: org.h2.Driver
    # username: sa
    #password: 
      url: jdbc:mysql://localhost:3306/pmamagerdb
      driverClassName: com.mysql.cj.jdbc.Driver
      username: root
      password: 1411
  # h2:
  #   console:
  #     enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  data:
    mongodb:
      host: localhost
      port: 27017
      database: pmamagerdb
app:
  general:
    pageSize: 3
  security:
    masterApiKey: thekey
    expirationDays: 2