server:
  servlet:
    context-path: /

spring:
  application:
    name: PManager
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
app:
  pageSize: 3